
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://106.12.35.31/oa?characterEncodeing=utf-8&useSSL=false&serverTimezone=GMT%2b8
  jpa:
    show-sql: true
server:
  port: 80

